env:
    global:
        - REPO_DIR=Shapely
        - PLAT=x86_64

language: generic
services: docker
os: linux

jobs:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
      - os: linux
        arch: arm64-graviton2
        dist: focal
        virt: vm
        group: edge
        env:
          - MB_PYTHON_VERSION=3.6
          - PLAT=aarch64
          - NP_BUILD_DEP=numpy>=1.17.3
          - NP_TEST_DEP=numpy>=1.17.3
          - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
          - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.7
          - PLAT=aarch64
          - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
          - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.8
          - PLAT=aarch64
          - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
          - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}

before_install:
    - git clone https://github.com/Toblerity/Shapely
    - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
    - BUILD_DEPENDS="$NP_BUILD_DEP cython==0.29.21 wheel==0.31.1"
    - TEST_DEPENDS="$NP_TEST_DEP attrs==19.1.0 pytest==4.0.2 mock;python_version<'3.4' boto3 packaging hypothesis==4.38.1 wheel==0.31.1 $GEN_DEPS"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT
after_success:
    - pip install twine
    - twine upload  ${TRAVIS_BUILD_DIR}/wheelhouse/*
